backend:
  name: git-gateway
  branch: master

media_folder: "Imagens"
public_folder: "/Imagens"

collections:
  - name: "reviews_2026_1"
    label: "Reviews 2026 (Jan-Jul)"
    folder: "2026/1"
    create: true
    slug: "{{album | slugify}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layout.njk" }
      - { label: "Data da Postagem", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Álbum", name: "album", widget: "string" }
      - { label: "Artista", name: "artista", widget: "string" }
      - { label: "Frase de Impacto", name: "frase_impacto", widget: "string" }
      - { label: "Data de Lançamento (Ano)", name: "data_lancamento", widget: "string" }
      - { label: "Gênero", name: "genero", widget: "string" }
      - { label: "Duração", name: "duracao", widget: "string" }
      - { label: "Nota (0-100)", name: "nota", widget: "number" }
      - { label: "Capa do Álbum", name: "imagem", widget: "image" }
      - { label: "1. Contexto e Expectativa", name: "introducao", widget: "markdown" }
      - { label: "2. Análise Faixa a Faixa", name: "analise", widget: "markdown" }
      - { label: "3. Conclusão e Veredito", name: "conclusao", widget: "markdown" }

  - name: "artistas"
label: "Artistas"
folder: "src/artistas"
filter: {field: "artista", value: ".*"}
nested:
  depth: 2
create: true
slug: "{{slug}}"  # Usando slug para criar a URL amigável
path: "{{artista | slugify}}/index.md"  # Caminho para criar as pastas por letra
extension: "md"
format: "frontmatter"
fields:
  - { label: "Layout", name: "layout", widget: "hidden", default: "artista-layout.njk" }
  - { label: "Nome do Artista", name: "artista", widget: "string" }
  - { label: "Gênero Principal", name: "genero_principal", widget: "string" }
  - { label: "Foto do Banner", name: "foto_artista", widget: "image" }
  - { label: "Biografia/Texto", name: "body", widget: "markdown" }
